import { DashboardLayout } from "@/components/DashboardLayout";
import { FileDown, BarChart3, TrendingUp, Package, Receipt, ShoppingCart, FileText, Truck, Calendar, Filter } from "lucide-react";
import { mockProducts, mockRecentSales, mockDailySalesData, mockCategorySales } from "@/data/mockData";
import { useState } from "react";
import { toast } from "sonner";

type ExportFormat = "pdf" | "excel" | "csv";

const REPORTS = [
  { id:"daily_sales",      title:"Daily Sales Report",       desc:"Transactions by cashier, product and payment method", icon:BarChart3,    color:"#10b981" },
  { id:"outlet_sales",     title:"Outlet-wise Sales",         desc:"Compare performance across all store locations",      icon:TrendingUp,   color:"#0ea5e9" },
  { id:"product_sales",    title:"Product-wise Sales",        desc:"Top/bottom performers, slow movers, ABC analysis",    icon:Package,      color:"#f59e0b" },
  { id:"stock_movement",   title:"Stock Movement Report",     desc:"Inventory changes, adjustments and transfers",        icon:ShoppingCart, color:"#a78bfa" },
  { id:"gst_report",       title:"GST Report",                desc:"Tax by rate slab, HSN summary, GSTR-1 compatible",   icon:Receipt,      color:"#f43f5e" },
  { id:"purchase_report",  title:"Purchase Report",           desc:"Supplier orders, GRN records, pending payables",      icon:Truck,        color:"#38bdf8" },
];

/* ── CSV generation helpers ── */
function toCSV(rows: string[][]): string {
  return rows.map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
}

function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

/* ── Simple PDF via HTML/CSS printed as blob ── */
function generatePDFHtml(title: string, tableHtml: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8">
  <title>${title}</title>
  <style>
    body{font-family:Arial,sans-serif;font-size:12px;margin:20px;color:#111}
    h1{font-size:18px;margin-bottom:4px}
    .sub{color:#666;font-size:11px;margin-bottom:16px}
    table{width:100%;border-collapse:collapse}
    th{background:#f3f4f6;text-align:left;padding:6px 10px;font-size:10px;text-transform:uppercase;letter-spacing:.05em;border-bottom:2px solid #e5e7eb}
    td{padding:6px 10px;border-bottom:1px solid #f3f4f6;font-size:11px}
    .footer{margin-top:20px;font-size:10px;color:#9ca3af}
  </style></head><body>
  <h1>${title}</h1>
  <div class="sub">Generated by Bizzy POS · ${new Date().toLocaleString("en-IN")}</div>
  ${tableHtml}
  <div class="footer">© Bizzy POS System · Confidential</div>
  </body></html>`;
}

function getReportData(id: string): { headers: string[]; rows: (string|number)[][] } {
  switch (id) {
    case "daily_sales":
      return {
        headers: ["Invoice ID","Items","Total (₹)","Payment","Cashier","Outlet","Date"],
        rows: mockRecentSales.map((s) => [s.id, s.items, s.total, s.paymentMethod, s.cashier, s.outletId||"", new Date(s.date).toLocaleString("en-IN")]),
      };
    case "product_sales":
    case "stock_movement":
      return {
        headers: ["Product","SKU","Category","Cost (₹)","Price (₹)","GST %","Stock","Min Stock","Margin %"],
        rows: mockProducts.map((p) => [
          p.name, p.sku, p.category, p.costPrice, p.sellingPrice, p.gstPercent,
          p.currentStock, p.minStockLevel,
          (((p.sellingPrice - p.costPrice) / p.sellingPrice) * 100).toFixed(1) + "%",
        ]),
      };
    case "outlet_sales":
      return {
        headers: ["Day","Sales (₹)","vs Prev"],
        rows: mockDailySalesData.map((d, i) => [
          d.day, d.sales,
          i > 0 ? ((d.sales - mockDailySalesData[i-1].sales) / mockDailySalesData[i-1].sales * 100).toFixed(1)+"%" : "—",
        ]),
      };
    case "gst_report":
      return {
        headers: ["Product","Category","Price (₹)","GST %","GST Amount (₹)"],
        rows: mockProducts.map((p) => [
          p.name, p.category, p.sellingPrice, p.gstPercent,
          ((p.sellingPrice * p.gstPercent) / 100).toFixed(2),
        ]),
      };
    case "purchase_report":
    default:
      return {
        headers: ["Category","Sales Share %"],
        rows: mockCategorySales.map((c) => [c.name, c.value+"%"]),
      };
  }
}

function exportReport(reportId: string, reportTitle: string, format: ExportFormat) {
  const { headers, rows } = getReportData(reportId);
  const date = new Date().toISOString().slice(0,10);
  const fname = `bizzy_${reportId}_${date}`;

  if (format === "csv") {
    const csv = toCSV([headers, ...rows.map((r) => r.map(String))]);
    downloadBlob(csv, `${fname}.csv`, "text/csv");
    return;
  }

  if (format === "excel") {
    // TSV with BOM for Excel compatibility
    const tsv = "\uFEFF" + [headers, ...rows.map((r) => r.map(String))]
      .map((r) => r.join("\t")).join("\n");
    downloadBlob(tsv, `${fname}.xls`, "application/vnd.ms-excel");
    return;
  }

  if (format === "pdf") {
    const thead = `<tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr>`;
    const tbody = rows.map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join("")}</tr>`).join("");
    const tableHtml = `<table><thead>${thead}</thead><tbody>${tbody}</tbody></table>`;
    const html = generatePDFHtml(reportTitle, tableHtml);
    const w = window.open("", "_blank");
    if (w) {
      w.document.write(html);
      w.document.close();
      w.focus();
      setTimeout(() => { w.print(); }, 400);
    }
  }
}

const Reports = () => {
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo,   setDateTo]   = useState("");

  return (
    <DashboardLayout>
      <div className="space-y-5">
        <div className="flex items-start justify-between flex-wrap gap-3">
          <div>
            <h1 className="text-2xl font-black text-foreground" style={{ fontFamily:"Syne,sans-serif" }}>Reports</h1>
            <p className="text-sm text-muted-foreground mt-0.5">Generate, analyse, and export business reports</p>
          </div>
          {/* Date range filter */}
          <div className="flex items-center gap-2 flex-wrap">
            <div className="flex items-center gap-2 px-3 py-2 rounded-xl border border-border bg-white text-xs">
              <Calendar className="w-3.5 h-3.5 text-muted-foreground" />
              <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)}
                className="bg-transparent text-foreground focus:outline-none w-28" />
              <span className="text-muted-foreground">→</span>
              <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)}
                className="bg-transparent text-foreground focus:outline-none w-28" />
            </div>
          </div>
        </div>

        {/* Summary strip */}
        <div className="grid grid-cols-3 gap-3">
          {[
            { label:"Today's Revenue",    value:"₹28,450", color:"#10b981" },
            { label:"Total Transactions", value:"156",      color:"#0ea5e9" },
            { label:"Avg Order Value",    value:"₹182",     color:"#f59e0b" },
          ].map(({ label, value, color }) => (
            <div key={label} className="rounded-2xl border border-border p-4 bg-white pos-shadow">
              <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">{label}</p>
              <p className="text-2xl font-black mt-1 font-mono" style={{ color }}>{value}</p>
            </div>
          ))}
        </div>

        {/* Report cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {REPORTS.map((r) => {
            const Icon = r.icon;
            return (
              <div key={r.id} className="rounded-2xl border border-border pos-shadow p-5 flex flex-col gap-4 bg-white hover:border-border/60 transition-all">
                <div className="flex items-start justify-between">
                  <div className="w-11 h-11 rounded-xl flex items-center justify-center" style={{ background:`${r.color}18`, color:r.color }}>
                    <Icon className="w-5 h-5" />
                  </div>
                  <span className="text-[10px] font-bold px-2 py-0.5 rounded-lg uppercase tracking-wider"
                    style={{ background:`${r.color}12`, color:r.color }}>Report</span>
                </div>
                <div className="flex-1">
                  <h3 className="font-bold text-sm text-foreground">{r.title}</h3>
                  <p className="text-xs text-muted-foreground mt-1 leading-relaxed">{r.desc}</p>
                </div>
                {/* Download buttons */}
                <div className="flex gap-2 pt-1 border-t border-border">
                  {(["pdf","excel","csv"] as ExportFormat[]).map((fmt) => (
                    <button key={fmt}
                      onClick={() => {
                        exportReport(r.id, r.title, fmt);
                        toast.success(`${r.title} exported as ${fmt.toUpperCase()}`);
                      }}
                      className="flex-1 flex items-center justify-center gap-1 py-2 rounded-xl text-xs font-bold border border-border text-muted-foreground transition-all hover:text-foreground"
                      onMouseEnter={(e) => { e.currentTarget.style.background = `${r.color}12`; e.currentTarget.style.color = r.color; e.currentTarget.style.borderColor = `${r.color}40`; }}
                      onMouseLeave={(e) => { e.currentTarget.style.background = ""; e.currentTarget.style.color = ""; e.currentTarget.style.borderColor = ""; }}>
                      <FileDown className="w-3 h-3" />
                      {fmt.toUpperCase()}
                    </button>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </DashboardLayout>
  );
};
export default Reports;
